export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";

export const SAVE_IMG = "SAVE_IMG";

export const SAVE_IMG_FAILED = "SAVE_IMG_FAILED";

export const SET_STATE_SIGNED_IN = "SET_STATE_SIGNED_IN";
export const SET_STATE_SIGNED_OUT = "SET_STATE_SIGNED_OUT";

export const GET_IMAGE_DATA = "GET_IMAGE_DATA";
export const DELETE_IMAGE_DATA = "DELETE_IMAGE_DATA";

export const SET_PEN_WIDTH = "SET_PEN_WIDTH";
export const SET_PEN_COLOR = "SET_PEN_COLOR";

export const SET_SHAPE = "SET_SHAPE";
export const ERASE = "ERASE";

export const GET_DB_IMAGES = "GET_DB_IMAGES";
export const GET_DB_IMAGES_SUCCEED = "GET_DB_IMAGES_SUCCEED";
export const GET_DB_IMAGES_FAILED = "GET_DB_IMAGES_FAILED";

export const GET_RECENT_IMAGES = "GET_RECENT_IMAGES";
export const GET_RECENT_IMAGES_SUCCEED = "GET_RECENT_IMAGES_SUCCEED";
export const GET_RECENT_IMAGES_FAILED = "GET_RECENT_IMAGES_FAILED";

export const GET_USER_IMGS = "GET_USER_IMGS";
export const GET_USER_IMGS_SUCCEED = "GET_USER_IMGS_SUCCEED";
export const GET_USER_IMGS_FAILED = "GET_USER_IMGS_FAILED";

export const CLEAR_STATE = "CLEAR_STATE";
